name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Lint
      id: lint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Lint
        setup-command: npm install --legacy-peer-deps
        command: npm run lint
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LINT_RESULTS: "${{steps.lint.outputs.result}}"
      with:
        runners: lint
